-- Function name: FMTH(fileman_date_time))
-- Convert fileman date/time into $H
--
-- Input parameters:
-- fileman_date_time: (required) fileman formatted date and time
--
-- Output:
--
-- Returns: Returns the converted date in $H format

-- Example:
--
-- SELECT FMTH("3200101.100000")
-- Result: 65379,36000
--
-- SELECT FMDATE("3200101")
-- Result: 65379,0
--
DROP FUNCTION IF EXISTS FMTH(INTEGER);
CREATE FUNCTION FMTH(INTEGER) RETURNS VARCHAR AS $$FMTH^XLFDT;

DROP FUNCTION IF EXISTS FMTH(INTEGER,INTEGER);
CREATE FUNCTION FMTH(INTEGER,INTEGER) RETURNS INTEGER AS $$FMTH^XLFDT;

DROP FUNCTION IF EXISTS FMTH(NUMERIC);
CREATE FUNCTION FMTH(NUMERIC) RETURNS VARCHAR AS $$FMTH^XLFDT;

DROP FUNCTION IF EXISTS FMTH(NUMERIC,INTEGER);
CREATE FUNCTION FMTH(NUMERIC,INTEGER) RETURNS INTEGER AS $$FMTH^XLFDT;