DROP FUNCTION IF EXISTS FUNCTION IFNULL(VARCHAR);
CREATE FUNCTION IFNULL(VARCHAR) RETURNS VARCHAR AS $$IFNULL^%YDBOCTOVISTAF;

DROP FUNCTION IF EXISTS FUNCTION IFNULL(VARCHAR,INTEGER);
CREATE FUNCTION IFNULL(VARCHAR,INTEGER) RETURNS INTEGER AS $$IFNULL^%YDBOCTOVISTAF;

DROP FUNCTION IF EXISTS FUNCTION IFNULL(VARCHAR,VARCHAR);
CREATE FUNCTION IFNULL(VARCHAR,VARCHAR) RETURNS VARCHAR AS $$IFNULL^%YDBOCTOVISTAF;
