DROP FUNCTION IF EXISTS TIMESTAMP();
CREATE FUNCTION TIMESTAMP() RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

DROP FUNCTION IF EXISTS TIMESTAMP(CHAR);
CREATE FUNCTION TIMESTAMP(CHAR) RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

DROP FUNCTION IF EXISTS TIMESTAMP(VARCHAR);
CREATE FUNCTION TIMESTAMP(VARCHAR) RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

