CREATE FUNCTION TIMESTAMP() RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;
CREATE FUNCTION TIMESTAMP(CHAR) RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;
CREATE FUNCTION TIMESTAMP(VARCHAR) RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

