DROP FUNCTION IF EXISTS REVERSE(INTEGER);
CREATE FUNCTION REVERSE(INTEGER) RETURNS VARCHAR AS $REVERSE;

DROP FUNCTION IF EXISTS REVERSE(VARCHAR);
CREATE FUNCTION REVERSE(VARCHAR) RETURNS VARCHAR AS $REVERSE;
