DROP FUNCTION IF EXISTS FIND(VARCHAR,VARCHAR);
CREATE FUNCTION FIND(VARCHAR,VARCHAR) RETURNS INTEGER AS $FIND;

DROP FUNCTION IF EXISTS FIND(VARCHAR,VARCHAR,INTEGER);
CREATE FUNCTION FIND(VARCHAR,VARCHAR,INTEGER) RETURNS INTEGER AS $FIND;