CREATE FUNCTION MPIECE(VARCHAR,VARCHAR) RETURNS VARCHAR AS $PIECE;
CREATE FUNCTION MPIECE(VARCHAR,VARCHAR,INTEGER) RETURNS VARCHAR AS $PIECE;
CREATE FUNCTION MPIECE(VARCHAR,VARCHAR,INTEGER,INTEGER) RETURNS VARCHAR AS $PIECE;
