CREATE FUNCTION IFNULL(VARCHAR) RETURNS VARCHAR AS $$IFNULL^%YDBOCTOVISTAF;
CREATE FUNCTION IFNULL(VARCHAR,INTEGER) RETURNS INTEGER AS $$IFNULL^%YDBOCTOVISTAF;
CREATE FUNCTION IFNULL(VARCHAR,VARCHAR) RETURNS VARCHAR AS $$IFNULL^%YDBOCTOVISTAF;
