DROP FUNCTION IF EXISTS FUNCTION TIMESTAMP();
CREATE FUNCTION TIMESTAMP() RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

DROP FUNCTION IF EXISTS FUNCTION TIMESTAMP(CHAR);
CREATE FUNCTION TIMESTAMP(CHAR) RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

DROP FUNCTION IF EXISTS FUNCTION TIMESTAMP(VARCHAR);
CREATE FUNCTION TIMESTAMP(VARCHAR) RETURNS VARCHAR AS $$TIMESTAMP^%YDBOCTOVISTAF;

